# Generated by Django 3.0.5 on 2020-07-19 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0001_initial'),
        ('collect', '0002_auto_20200719_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lastvisit',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Collect'),
        ),
        migrations.AddField(
            model_name='lastvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='history',
            name='collect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect.Collect'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
